on:
  create:
  release:
    types: [created]

name: Handle Release
jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        result: [cli, datasette, pypack1]
    name: ${{ matrix.result }} artifacts
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: support ape bins and SSL things
        run: bash ./.github/scripts/setup
      - name: build Cosmo
        run: bash ./.github/scripts/cosmo
      - name: build ${{ matrix.result }}
        env:
          ZFILENAME: ${{ matrix.result }}
        run: bash ./.github/scripts/${{ matrix.result }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: "${{ matrix.result }}*.zip"
          overwrite: true
