on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: support ape bins and SSL things
        run: bash ./.github/scripts/setup
      - name: build Cosmo
        run: bash ./.github/scripts/cosmo
      - name: build aarch64
        run: bash ./.github/scripts/aarch64-build
      - name: build x86_64
        run: bash ./.github/scripts/x86-build
      - name: combine
        run: bash ./.github/scripts/combine
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: "results*.zip"
          overwrite: true
